# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
# docker-compose.yml
services:
  backend:
    container_name: prj2-09-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/PRJ2-Database-09
      - SPRING_DATASOURCE_USERNAME=PRJ2-User-09
      - SPRING_DATASOURCE_PASSWORD=PRJ2-Password-09
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

  frontend:
    container_name: prj2-09-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - PUBLIC_API_BASE=http://localhost:8080/api/v1
    depends_on:
      - backend
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

  postgres:
    image: postgres:13
    container_name: prj2-09-postgres-database
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=PRJ2-Database-09
      - POSTGRES_USER=PRJ2-User-09
      - POSTGRES_PASSWORD=PRJ2-Password-09
      # Add an environment variable to help with database cleanup scripts
      - POSTGRES_CLEAN_ON_START=${CLEAN_DB:-false}
    volumes:
      - ${FRESH_DB:-db_data}:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

volumes:
  db_data:
  # This temporary volume will be created and destroyed automatically
  fresh_db:
    driver: local
