package io.github.fontysvenlo.ais.persistence;

import io.github.fontysvenlo.ais.datarecords.EmployeeData;
import io.github.fontysvenlo.ais.persistence.api.EmployeeRepository;

import javax.sql.DataSource;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * This class knows everything about storing and retrieving customers from the database.
 * At the moment only returns dummy object with an id that is set.
 * Normally it will connect to a database and do all the handling.
 */
class EmployeeRepositoryImpl implements EmployeeRepository {

    private final DataSource db;
    //private final List<EmployeeData> emplyees = new ArrayList<>(Arrays.asList(new EmployeeData(1, "John", "Doe", LocalDate.of(2025, 1, 1))));
    private final List<EmployeeData> emplyees = new ArrayList<>();

    public EmployeeRepositoryImpl(DBConfig config) {
        this.db = DBProvider.getDataSource(config);
    }

    @Override
    public EmployeeData add(EmployeeData employeeData) {
        // Create dummy EmployeeData object with id. Normally, the id would be generated by the database
        int maxId = emplyees.stream().mapToInt(EmployeeData::id).max().orElse(0);
        EmployeeData employeeDataWithId = new EmployeeData( maxId++, employeeData.Firstname(), employeeData.Lastname(), employeeData.Email(), employeeData.Password(), employeeData.Type());
        emplyees.add(employeeDataWithId);
        return employeeDataWithId;
    }

    @Override
    public EmployeeData update(EmployeeData employeeData) {
        return null;
    }

    @Override
    public EmployeeData delete(String id) {
        // TODO: Implement the actual database storage
        return null;
    }

    @Override
    public EmployeeData getOne(String id) {
        try {
            int employeeId = Integer.parseInt(id);
            System.out.println("Employee ID: " + employeeId);
            return emplyees.stream()
                    .filter(employee -> employee.id() == employeeId)
                    .findFirst()
                    .orElse(null);
        } catch (NumberFormatException e) {
            return null; // Return null if the ID isn't a valid integer
        }
    }

    @Override
    public List<EmployeeData> getAll() {
        // TODO: Implement the actual database storage
        // For now, return a dummy list
        return Collections.unmodifiableList(emplyees);
    }
}
